class CharactersService {
    getCharacters() {
        var characters = [{
                character_id: 1,
                character_name: "Frendat Smeltfoot",
                character_race: "Gnome: Deep (Svirfneblin)",
                character_class: "Artificer",
                character_build: "Alchemist",
                character_max_level: 20,
            },
            {
                character_id: 2,
                character_name: "Morbok the Red",
                character_race: "Hobgoblin of the Feywild (UA)",
                character_class: "Artificer",
                character_build: "Armorer",
                character_max_level: 20,
            },
            {
                character_id: 3,
                character_name: "Fenphina d'Sivis",
                character_race: "Gnome: Mark of Scribing",
                character_class: "Artificer",
                character_build: "Artillerist",
                character_max_level: 20,
            },
            {
                character_id: 4,
                character_name: "Kars’ten Gi'parakk",
                character_race: "Gith: Githyanki",
                character_class: "Artificer",
                character_build: "Battle Smith",
                character_max_level: 20,
            },
            {
                character_id: 5,
                character_name: "Balasar Frostwyrm",
                character_race: "Dragonborn: Chromatic",
                character_class: "Barbarian",
                character_build: "Path of Wild Magic",
                character_max_level: 20,
            },
            {
                character_id: 6,
                character_name: "Vamana Firehammer",
                character_race: "Dwarf: Gray (Duergar)",
                character_class: "Barbarian",
                character_build: "Path of the Ancestral Guardian",
                character_max_level: 20,
            },
            {
                character_id: 7,
                character_name: "Orikour Whiteforge",
                character_race: "Dwarf: Mountain",
                character_class: "Barbarian",
                character_build: "Path of the Battlerager",
                character_max_level: 20,
            },
            {
                character_id: 8,
                character_name: "Fasken Stronghorn",
                character_race: "Minotaur",
                character_class: "Barbarian",
                character_build: "Path of the Beast",
                character_max_level: 20,
            },
            {
                character_id: 9,
                character_name: "Amethyst Whitestone",
                character_race: "Genasi: Earth",
                character_class: "Barbarian",
                character_build: "Path of the Berserker",
                character_max_level: 20,
            },
            {
                character_id: 10,
                character_name: "Varthan Rockhide Nulakelo",
                character_race: "Goliath",
                character_class: "Barbarian",
                character_build: "Path of the Storm Herald",
                character_max_level: 20,
            },
            {
                character_id: 11,
                character_name: "Urodak Skullcleaver",
                character_race: "Orc of Exandria",
                character_class: "Barbarian",
                character_build: "Path of the Totem Warrior",
                character_max_level: 20,
            },
            {
                character_id: 12,
                character_name: "Mahogany Winterwolf",
                character_race: "Shifter: Beasthide",
                character_class: "Barbarian",
                character_build: "Path of the Zealot",
                character_max_level: 20,
            },
            {
                character_id: 13,
                character_name: "Bruhd Arkenviir",
                character_race: "Half-Elf: Drow",
                character_class: "Bard",
                character_build: "College of Creation",
                character_max_level: 20,
            },
            {
                character_id: 14,
                character_name: "Ghilanna Elendhen",
                character_race: "Half-Elf: Aquatic",
                character_class: "Bard",
                character_build: "College of Eloquence",
                character_max_level: 20,
            },
            {
                character_id: 15,
                character_name: "Rexius Trannyth",
                character_race: "Tiefling: Fierna",
                character_class: "Bard",
                character_build: "College of Glamour",
                character_max_level: 20,
            },
            {
                character_id: 16,
                character_name: "Malakos Duskwalker",
                character_race: "Tiefling: Mammon",
                character_class: "Bard",
                character_build: "College of Lore",
                character_max_level: 20,
            },
            {
                character_id: 17,
                character_name: "Surina Brightscale",
                character_race: "Dragonborn: Gem",
                character_class: "Bard",
                character_build: "College of Spirits",
                character_max_level: 20,
            },
            {
                character_id: 18,
                character_name: "Damine Zangold",
                character_race: "Tiefling: Glasya",
                character_class: "Bard",
                character_build: "College of Swords",
                character_max_level: 20,
            },
            {
                character_id: 19,
                character_name: "Brenwan Blademaster",
                character_race: "Aasimar: Fallen",
                character_class: "Bard",
                character_build: "College of Valor",
                character_max_level: 20,
            },
            {
                character_id: 20,
                character_name: "Arala Shadowdancer",
                character_race: "Aasimar: Protector",
                character_class: "Bard",
                character_build: "College of Whispers",
                character_max_level: 20,
            },
            {
                character_id: 21,
                character_name: "Selanar Fenthana",
                character_race: "Elf: Sea",
                character_class: "Blood Hunter",
                character_build: "Order of the Ghostslayer",
                character_max_level: 20,
            },
            {
                character_id: 22,
                character_name: "Vestia Blacksong",
                character_race: "Halfling: Stout",
                character_class: "Blood Hunter",
                character_build: "Order of the Lycan",
                character_max_level: 20,
            },
            {
                character_id: 23,
                character_name: "Cyclone Wintersgale",
                character_race: "Genasi: Air",
                character_class: "Blood Hunter",
                character_build: "Order of the Mutant",
                character_max_level: 20,
            },
            {
                character_id: 24,
                character_name: "Nilga Moldfoot",
                character_race: "Goblin",
                character_class: "Blood Hunter",
                character_build: "Order of the Profane Soul",
                character_max_level: 20,
            },
            {
                character_id: 25,
                character_name: "Tothin d'Medani",
                character_race: "Half-Elf: Mark of Detection",
                character_class: "Cleric",
                character_build: "Arcana Domain",
                character_max_level: 20,
            },
            {
                character_id: 26,
                character_name: "Rhaz Blackscale",
                character_race: "Lizardfolk",
                character_class: "Cleric",
                character_build: "Death Domain",
                character_max_level: 20,
            },
            {
                character_id: 27,
                character_name: "Theratis Wyrmsbane",
                character_race: "Dwarf: Hill",
                character_class: "Cleric",
                character_build: "Forge Domain",
                character_max_level: 20,
            },
            {
                character_id: 28,
                character_name: "Kedehna Calloway",
                character_race: "Reborn",
                character_class: "Cleric",
                character_build: "Grave Domain",
                character_max_level: 20,
            },
            {
                character_id: 29,
                character_name: "Gangahr Sak",
                character_race: "Gith: Githzerai",
                character_class: "Cleric",
                character_build: "Knowledge Domain",
                character_max_level: 20,
            },
            {
                character_id: 30,
                character_name: "Aaliyah d'Deneith",
                character_race: "Human: Mark of Sentinel",
                character_class: "Cleric",
                character_build: "Life Domain",
                character_max_level: 20,
            },
            {
                character_id: 31,
                character_name: "Butir Aashta",
                character_race: "Half-Orc: Mark of Finding",
                character_class: "Cleric",
                character_build: "Light Domain",
                character_max_level: 20,
            },
            {
                character_id: 32,
                character_name: "Screech Sharpbeak",
                character_race: "Owlin",
                character_class: "Cleric",
                character_build: "Nature Domain",
                character_max_level: 20,
            },
            {
                character_id: 33,
                character_name: "Thraldov Irontusk",
                character_race: "Loxodon",
                character_class: "Cleric",
                character_build: "Order Domain",
                character_max_level: 20,
            },
            {
                character_id: 34,
                character_name: "Burghard d'Vadalis",
                character_race: "Human: Mark of Handling",
                character_class: "Cleric",
                character_build: "Peace Domain",
                character_max_level: 20,
            },
            {
                character_id: 35,
                character_name: "Tempest Fury",
                character_race: "Genasi: Water",
                character_class: "Cleric",
                character_build: "Tempest Domain",
                character_max_level: 20,
            },
            {
                character_id: 36,
                character_name: "Marigold Swiftpaw",
                character_race: "Shifter: Wildhunt",
                character_class: "Cleric",
                character_build: "Trickery Domain",
                character_max_level: 20,
            },
            {
                character_id: 37,
                character_name: "Ghatara Mohan",
                character_race: "Kalashtar",
                character_class: "Cleric",
                character_build: "Twilight Domain",
                character_max_level: 20,
            },
            {
                character_id: 38,
                character_name: "Doctor Metalskin",
                character_race: "Warforged",
                character_class: "Cleric",
                character_build: "War Domain",
                character_max_level: 20,
            },
            {
                character_id: 39,
                character_name: "Kareth Aravaal",
                character_race: "Kalashtar",
                character_class: "Druid",
                character_build: "Circle of Dreams",
                character_max_level: 20,
            },
            {
                character_id: 40,
                character_name: "Alluvial d'Medani",
                character_race: "Half-Elf: Mark of Detection",
                character_class: "Druid",
                character_build: "Circle of Spores",
                character_max_level: 20,
            },
            {
                character_id: 41,
                character_name: "Ohnira Nightwalker",
                character_race: "Gith: Githzerai",
                character_class: "Druid",
                character_build: "Circle of Stars",
                character_max_level: 20,
            },
            {
                character_id: 42,
                character_name: "Lavinia d'Jorasco",
                character_race: "Halfling: Mark of Healing",
                character_class: "Druid",
                character_build: "Circle of Wildfire",
                character_max_level: 20,
            },
            {
                character_id: 43,
                character_name: "Darhana d'Vadalis",
                character_race: "Human: Mark of Handling",
                character_class: "Druid",
                character_build: "Circle of the Land (Arctic)",
                character_max_level: 20,
            },
            {
                character_id: 44,
                character_name: "Oceana Deepwater",
                character_race: "Genasi: Water",
                character_class: "Druid",
                character_build: "Circle of the Land (Coast)",
                character_max_level: 20,
            },
            {
                character_id: 45,
                character_name: "Danhorn Steamkettle",
                character_race: "Halfling: Ghostwise",
                character_class: "Druid",
                character_build: "Circle of the Land (Desert)",
                character_max_level: 20,
            },
            {
                character_id: 46,
                character_name: "Soliana Gladewalker",
                character_race: "Elf: Aereni Wood",
                character_class: "Druid",
                character_build: "Circle of the Land (Forest)",
                character_max_level: 20,
            },
            {
                character_id: 47,
                character_name: "Loravyre d'Tharashk",
                character_race: "Human: Mark of Finding",
                character_class: "Druid",
                character_build: "Circle of the Land (Grassland)",
                character_max_level: 20,
            },
            {
                character_id: 48,
                character_name: "Thallia Merrybead",
                character_race: "Fairy",
                character_class: "Druid",
                character_build: "Circle of the Land (Mountain)",
                character_max_level: 20,
            },
            {
                character_id: 49,
                character_name: "Drux Hungryjaw",
                character_race: "Lizardfolk",
                character_class: "Druid",
                character_build: "Circle of the Land (Swamp)",
                character_max_level: 20,
            },
            {
                character_id: 50,
                character_name: "Raldarus Do'Veldrin",
                character_race: "Half-Elf: Drow",
                character_class: "Druid",
                character_build: "Circle of the Land (Underdark)",
                character_max_level: 20,
            },
            {
                character_id: 51,
                character_name: "Rustle Blackfeather",
                character_race: "Kenku",
                character_class: "Druid",
                character_build: "Circle of the Moon",
                character_max_level: 20,
            },
            {
                character_id: 52,
                character_name: "Daefina Burdun",
                character_race: "Firbolg",
                character_class: "Druid",
                character_build: "Circle of the Shepherd",
                character_max_level: 20,
            },
            {
                character_id: 53,
                character_name: "Melwen Moonarrow",
                character_race: "Elf: High",
                character_class: "Fighter",
                character_build: "Arcane Archer",
                character_max_level: 20,
            },
            {
                character_id: 54,
                character_name: "Urghat Speartooth",
                character_race: "Orc",
                character_class: "Fighter",
                character_build: "Battle Master",
                character_max_level: 20,
            },
            {
                character_id: 55,
                character_name: "Murzush Tuskeater",
                character_race: "Orc of Eberron",
                character_class: "Fighter",
                character_build: "Cavalier",
                character_max_level: 20,
            },
            {
                character_id: 56,
                character_name: "Goradhall Flametongue",
                character_race: "Dragonborn: Metalic",
                character_class: "Fighter",
                character_build: "Champion",
                character_max_level: 20,
            },
            {
                character_id: 57,
                character_name: "Dordak Steelstep",
                character_race: "Minotaur",
                character_class: "Fighter",
                character_build: "Echo Knight",
                character_max_level: 20,
            },
            {
                character_id: 58,
                character_name: "Ketrys Silvertail",
                character_race: "Tiefling: Variant Feral",
                character_class: "Fighter",
                character_build: "Eldritch Knight",
                character_max_level: 20,
            },
            {
                character_id: 59,
                character_name: "Endasare Anaedus",
                character_race: "Elf: Pallid",
                character_class: "Fighter",
                character_build: "Gunslinger",
                character_max_level: 20,
            },
            {
                character_id: 60,
                character_name: "Devorxa Duk'ich",
                character_race: "Gith: Githyanki",
                character_class: "Fighter",
                character_build: "Psi Warrior",
                character_max_level: 20,
            },
            {
                character_id: 61,
                character_name: "Katiri Stormheart",
                character_race: "Half-Orc",
                character_class: "Fighter",
                character_build: "Purple Dragon Knight",
                character_max_level: 20,
            },
            {
                character_id: 62,
                character_name: "Kurhen Bronzebottom",
                character_race: "Dwarf: Mountain",
                character_class: "Fighter",
                character_build: "Rune Knight",
                character_max_level: 20,
            },
            {
                character_id: 63,
                character_name: "Aranat Berthalas",
                character_race: "Elf: Shadar-kai",
                character_class: "Fighter",
                character_build: "Samurai",
                character_max_level: 20,
            },
            {
                character_id: 64,
                character_name: "Thora Browncloak",
                character_race: "Halfling: Lotusden",
                character_class: "Monk",
                character_build: "Way of Mercy",
                character_max_level: 20,
            },
            {
                character_id: 65,
                character_name: "Nidiliel d'Phiarlan",
                character_race: "Elf: Mark of Shadow",
                character_class: "Monk",
                character_build: "Way of Shadow",
                character_max_level: 20,
            },
            {
                character_id: 66,
                character_name: "Zeplo Shortsnout",
                character_race: "Kobold (UA)",
                character_class: "Monk",
                character_build: "Way of the Ascendant Dragon",
                character_max_level: 20,
            },
            {
                character_id: 67,
                character_name: "Vertrix Proudfoot",
                character_race: "Halfling: Ghostwise",
                character_class: "Monk",
                character_build: "Way of the Astral Self",
                character_max_level: 20,
            },
            {
                character_id: 68,
                character_name: "Taenya Leonelis",
                character_race: "Elf: Pallid",
                character_class: "Monk",
                character_build: "Way of the Cobalt Soul",
                character_max_level: 20,
            },
            {
                character_id: 69,
                character_name: "Edmar d'Orien",
                character_race: "Human: Mark of Passage",
                character_class: "Monk",
                character_build: "Way of the Drunken Master",
                character_max_level: 20,
            },
            {
                character_id: 70,
                character_name: "Erlan Quickfoot",
                character_race: "Harengon",
                character_class: "Monk",
                character_build: "Way of the Four Elements",
                character_max_level: 20,
            },
            {
                character_id: 71,
                character_name: "Jhaeros Cailen",
                character_race: "Elf: Wood",
                character_class: "Monk",
                character_build: "Way of the Kensei",
                character_max_level: 20,
            },
            {
                character_id: 72,
                character_name: "Trickling Brook",
                character_race: "Kenku",
                character_class: "Monk",
                character_build: "Way of the Long Death",
                character_max_level: 20,
            },
            {
                character_id: 73,
                character_name: "Aegrandir Highwood",
                character_race: "Elf: Valenar High",
                character_class: "Monk",
                character_build: "Way of the Open Hand",
                character_max_level: 20,
            },
            {
                character_id: 74,
                character_name: "Hallick Windfeather",
                character_race: "Aarakocra",
                character_class: "Monk",
                character_build: "Way of the Sun Soul",
                character_max_level: 20,
            },
            {
                character_id: 75,
                character_name: "Flint Fleshrender",
                character_race: "Shifter: Swiftstride",
                character_class: "Paladin",
                character_build: "Oath of Conquest",
                character_max_level: 20,
            },
            {
                character_id: 76,
                character_name: "Jesnorae Coltec",
                character_race: "Dragonborn",
                character_class: "Paladin",
                character_build: "Oath of Devotion",
                character_max_level: 20,
            },
            {
                character_id: 77,
                character_name: "Kemba Goldmane",
                character_race: "Leonin",
                character_class: "Paladin",
                character_build: "Oath of Glory",
                character_max_level: 20,
            },
            {
                character_id: 78,
                character_name: "Kithlyse Trickfoot",
                character_race: "Halfling: Lightfoot",
                character_class: "Paladin",
                character_build: "Oath of Redemption",
                character_max_level: 20,
            },
            {
                character_id: 79,
                character_name: "Xelbuk Stoneshell",
                character_race: "Tortle",
                character_class: "Paladin",
                character_build: "Oath of Vengeance",
                character_max_level: 20,
            },
            {
                character_id: 80,
                character_name: "Ethryn Doballath",
                character_race: "Triton",
                character_class: "Paladin",
                character_build: "Oath of the Ancients",
                character_max_level: 20,
            },
            {
                character_id: 81,
                character_name: "Jade Eye",
                character_race: "Tabaxi",
                character_class: "Paladin",
                character_build: "Oath of the Crown",
                character_max_level: 20,
            },
            {
                character_id: 82,
                character_name: "Sir Francis Drake",
                character_race: "Locathah",
                character_class: "Paladin",
                character_build: "Oath of the Open Sea",
                character_max_level: 20,
            },
            {
                character_id: 83,
                character_name: "g'Eehp Greenskin",
                character_race: "Grung",
                character_class: "Paladin",
                character_build: "Oath of the Watchers",
                character_max_level: 20,
            },
            {
                character_id: 84,
                character_name: "Zekantar Khalorel",
                character_race: "Elf: Dark (Drow)",
                character_class: "Paladin",
                character_build: "Oathbreaker",
                character_max_level: 20,
            },
            {
                character_id: 85,
                character_name: "Fury Tigerclaw",
                character_race: "Shifter: Longtooth",
                character_class: "Ranger",
                character_build: "Beast Master",
                character_max_level: 20,
            },
            {
                character_id: 132,
                character_name: "Erlathan Sylmaer",
                character_race: "Elf: Wood",
                character_class: "Ranger",
                character_build: "Drakewarden",
                character_max_level: 20,
            },
            {
                character_id: 86,
                character_name: "Alshana Feychild",
                character_race: "Elf: Eladrin (Variant)",
                character_class: "Ranger",
                character_build: "Fey Wanderer",
                character_max_level: 20,
            },
            {
                character_id: 87,
                character_name: "Sirlech Shadowmaster",
                character_race: "Tiefling: Variant Feral",
                character_class: "Ranger",
                character_build: "Gloom Stalker",
                character_max_level: 20,
            },
            {
                character_id: 88,
                character_name: "Breta Macfhi",
                character_race: "Hexblood",
                character_class: "Ranger",
                character_build: "Horizon Walker",
                character_max_level: 20,
            },
            {
                character_id: 89,
                character_name: "Togann Skullsmasher",
                character_race: "Bugbear",
                character_class: "Ranger",
                character_build: "Hunter (Colossus Slayer)",
                character_max_level: 20,
            },
            {
                character_id: 90,
                character_name: "Gloriana Brandybuck",
                character_race: "Halfling: Lotusden",
                character_class: "Ranger",
                character_build: "Hunter (Giant Killer)",
                character_max_level: 20,
            },
            {
                character_id: 91,
                character_name: "Therolos Thunderhooves",
                character_race: "Centaur",
                character_class: "Ranger",
                character_build: "Hunter (Horde Breaker)",
                character_max_level: 20,
            },
            {
                character_id: 92,
                character_name: "Belcrath Camphik",
                character_race: "Dragonborn: Ravenite",
                character_class: "Ranger",
                character_build: "Monster Slayer",
                character_max_level: 20,
            },
            {
                character_id: 93,
                character_name: "Gwendoline Bikker",
                character_race: "Elf: Aereni Wood",
                character_class: "Ranger",
                character_build: "Swarmkeeper",
                character_max_level: 20,
            },
            {
                character_id: 94,
                character_name: "Sarbis Ebonflame",
                character_race: "Tiefling: Feral",
                character_class: "Rogue",
                character_build: "Arcane Trickster",
                character_max_level: 20,
            },
            {
                character_id: 95,
                character_name: "Adream Shadowstepper",
                character_race: "Dhampir",
                character_class: "Rogue",
                character_build: "Assassin",
                character_max_level: 20,
            },
            {
                character_id: 96,
                character_name: "Quevara Silverbow",
                character_race: "Elf: Aereni High",
                character_class: "Rogue",
                character_build: "Inquisitive",
                character_max_level: 20,
            },
            {
                character_id: 97,
                character_name: "Garret d'Ghallanda",
                character_race: "Halfling: Mark of Hospitality",
                character_class: "Rogue",
                character_build: "Mastermind",
                character_max_level: 20,
            },
            {
                character_id: 98,
                character_name: "Hadra Widefeet",
                character_race: "Goblin",
                character_class: "Rogue",
                character_build: "Phantom",
                character_max_level: 20,
            },
            {
                character_id: 99,
                character_name: "Taleisin Briarwood",
                character_race: "Elf: Valenar Wood",
                character_class: "Rogue",
                character_build: "Scout",
                character_max_level: 20,
            },
            {
                character_id: 100,
                character_name: "Igna Drakerider",
                character_race: "Kobold",
                character_class: "Rogue",
                character_build: "Soulknife",
                character_max_level: 20,
            },
            {
                character_id: 101,
                character_name: "Zorrion Oakwood",
                character_race: "Elf: Eladrin",
                character_class: "Rogue",
                character_build: "Swashbuckler",
                character_max_level: 20,
            },
            {
                character_id: 102,
                character_name: "Gwiston d'Jorasco",
                character_race: "Halfling: Mark of Healing",
                character_class: "Rogue",
                character_build: "Thief",
                character_max_level: 20,
            },
            {
                character_id: 103,
                character_name: "Morilius Ashguard",
                character_race: "Tiefling: Mephistopheles",
                character_class: "Sorcerer",
                character_build: "Aberrant Mind",
                character_max_level: 20,
            },
            {
                character_id: 104,
                character_name: "Yaniir Wyvernclaw",
                character_race: "Tiefling: Dispater",
                character_class: "Sorcerer",
                character_build: "Clockwork Soul",
                character_max_level: 20,
            },
            {
                character_id: 105,
                character_name: "Learoma Blackcloak",
                character_race: "Aasimar: Variant",
                character_class: "Sorcerer",
                character_build: "Divine Soul",
                character_max_level: 20,
            },
            {
                character_id: 106,
                character_name: "Sylphira Willowbone",
                character_race: "Half-Elf",
                character_class: "Sorcerer",
                character_build: "Draconic Bloodline",
                character_max_level: 20,
            },
            {
                character_id: 107,
                character_name: "Nassirah Serpentskin",
                character_race: "Yuan-ti Pureblood",
                character_class: "Sorcerer",
                character_build: "Shadow Magic",
                character_max_level: 20,
            },
            {
                character_id: 108,
                character_name: "Norphanis d'Lyrandar",
                character_race: "Half-Elf: Mark of Storm",
                character_class: "Sorcerer",
                character_build: "Storm Sorcery",
                character_max_level: 20,
            },
            {
                character_id: 109,
                character_name: "Arshoon Shadowreaper",
                character_race: "Tiefling",
                character_class: "Sorcerer",
                character_build: "Wild Magic",
                character_max_level: 20,
            },
            {
                character_id: 110,
                character_name: "Cherioth Greyrider",
                character_race: "Satyr",
                character_class: "Warlock",
                character_build: "The Archfey",
                character_max_level: 20,
            },
            {
                character_id: 111,
                character_name: "Wygrem Iceblade",
                character_race: "Aasimar: Scourge",
                character_class: "Warlock",
                character_build: "The Celestial",
                character_max_level: 20,
            },
            {
                character_id: 112,
                character_name: "Mithtari Waverunner",
                character_race: "Tiefling: Levistus",
                character_class: "Warlock",
                character_build: "The Fathomless",
                character_max_level: 20,
            },
            {
                character_id: 113,
                character_name: "Phetari Bloodcrest",
                character_race: "Tiefling: Baalzebul",
                character_class: "Warlock",
                character_build: "The Fiend",
                character_max_level: 20,
            },
            {
                character_id: 114,
                character_name: "Sly Goldcrafter",
                character_race: "Tiefling: Variant",
                character_class: "Warlock",
                character_build: "The Genie",
                character_max_level: 20,
            },
            {
                character_id: 115,
                character_name: "Wox Darkblade",
                character_race: "Changeling",
                character_class: "Warlock",
                character_build: "The Great Old One",
                character_max_level: 20,
            },
            {
                character_id: 116,
                character_name: "Nalista Soulreaver",
                character_race: "Tiefling: Zariel",
                character_class: "Warlock",
                character_build: "The Hexblade",
                character_max_level: 20,
            },
            {
                character_id: 117,
                character_name: "Raven Royal",
                character_race: "Hexblood (UA)",
                character_class: "Warlock",
                character_build: "The Undead (UA)",
                character_max_level: 20,
            },
            {
                character_id: 118,
                character_name: "Utassi Birdcruncher",
                character_race: "Verdan",
                character_class: "Warlock",
                character_build: "The Undying",
                character_max_level: 20,
            },
            {
                character_id: 119,
                character_name: "Arwen Maplewood",
                character_race: "Elf: Eladrin (Variant)",
                character_class: "Wizard",
                character_build: "Bladesinging",
                character_max_level: 20,
            },
            {
                character_id: 120,
                character_name: "Tobias Steinmann",
                character_race: "Gnome: Rock",
                character_class: "Wizard",
                character_build: "Chronurgy Magic",
                character_max_level: 20,
            },
            {
                character_id: 121,
                character_name: "Jespatys Neldastar",
                character_race: "Dragonborn: Draconblood",
                character_class: "Wizard",
                character_build: "Graviturgy Magic",
                character_max_level: 20,
            },
            {
                character_id: 122,
                character_name: "Minwyn d'Sivis",
                character_race: "Gnome: Mark of Scribing",
                character_class: "Wizard",
                character_build: "Order of Scribes",
                character_max_level: 20,
            },
            {
                character_id: 123,
                character_name: "Thulnik d'Kundarak",
                character_race: "Dwarf: Mark of Warding",
                character_class: "Wizard",
                character_build: "School of Abjuration",
                character_max_level: 20,
            },
            {
                character_id: 124,
                character_name: "Mirabella Lindenbrook",
                character_race: "Half-Elf: Wood",
                character_class: "Wizard",
                character_build: "School of Conjuration",
                character_max_level: 20,
            },
            {
                character_id: 125,
                character_name: "Kodi Silverscar",
                character_race: "Vedalken",
                character_class: "Wizard",
                character_build: "School of Divination",
                character_max_level: 20,
            },
            {
                character_id: 126,
                character_name: "Lyndon Braveheart",
                character_race: "Human: Variant",
                character_class: "Wizard",
                character_build: "School of Enchantment",
                character_max_level: 20,
            },
            {
                character_id: 127,
                character_name: "Magma Embers",
                character_race: "Genasi: Fire",
                character_class: "Wizard",
                character_build: "School of Evocation",
                character_max_level: 20,
            },
            {
                character_id: 128,
                character_name: "Gimble Wedgesweeper",
                character_race: "Gnome: Forest",
                character_class: "Wizard",
                character_build: "School of Illusion",
                character_max_level: 20,
            },
            {
                character_id: 129,
                character_name: "Talia Whittlebones",
                character_race: "Human",
                character_class: "Wizard",
                character_build: "School of Necromancy",
                character_max_level: 20,
            },
            {
                character_id: 130,
                character_name: "Eilxina Stormbreaker",
                character_race: "Simic Hybrid",
                character_class: "Wizard",
                character_build: "School of Transmutation",
                character_max_level: 20,
            },
            {
                character_id: 131,
                character_name: "Kothuk Talbo",
                character_race: "Hobgoblin",
                character_class: "Wizard",
                character_build: "War Magic",
                character_max_level: 20,
            },
        ];

        var byProperty = function(prop) {
            return function(a, b) {
                if (typeof a[prop] == "number") {
                    return a[prop] - b[prop];
                } else {
                    return a[prop] < b[prop] ? -1 : a[prop] > b[prop] ? 1 : 0;
                }
            };
        };

        characters.sort(byProperty("character_build"));

        return characters;
    }
}